### ISSUE TITLE
problem quickloading purplish - component verbose not found

### ISSUE THREAD

**Issue by markhdavid** [Shirakumo/purplish#5]
Running Ubuntu Linux, SBCL, when I do (ql:quickload :purplish), I get the error eventually: Component "verbose" not found

Version details: 

Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

CBCL: 1.4.5.debian

**Comment by markhdavid** [comment]
Yes, I loaded radiance first. I attached a log from the Lisp REPL up to the error.

[purplish-radiance-sbcl-ubuntu-2019-02-02-log.txt](https://github.com/Shirakumo/purplish/files/2824854/purplish-radiance-sbcl-ubuntu-2019-02-02-log.txt)

**Comment by Shinmera** [comment]
I have no idea what this could be about. Quicklisp clearly downloaded Verbose, so it should be able to find it. It seems more like a Quicklisp or ASDF configuration problem than a Purplish or Radiance problem.

**Comment by markhdavid** [comment]
I got the scoop. This is a problem with Quicklisp and :defsystem-depends-on dependencies. A workaround for this would be to load system "verbose" first, e.g., `(progn (ql:quickload :verbose) (ql:quickload :purplish))`. If this is not happening to you, it's because this only happens if verbose is not already available, but in your environment it's always already available. And, also, it only happens the first time you try.

To reliably reproduce, remove your ~/quicklisp directory, then in a new Lisp evaluate the following forms in order:

> `(load "~/quicklisp.lisp")`
> `(quicklisp-quickstart:install)`
> `(ql-dist:install-dist "http://dist.tymoon.eu/shirakumo.txt")`
> `(ql:quickload :radiance)`
> `(ql:quickload :purplish)`

I'm attaching a 2 logs, 1 failing and 1 succeeding with the workaround.

[purplish-radiance-sbcl-ubuntu-2019-02-06-log.txt](https://github.com/Shirakumo/purplish/files/2837818/purplish-radiance-sbcl-ubuntu-2019-02-06-log.txt)
[workaround-purplish-radiance-sbcl-ubuntu-2019-0206-log.txt](https://github.com/Shirakumo/purplish/files/2837817/workaround-purplish-radiance-sbcl-ubuntu-2019-0206-log.txt)

**Comment by Shinmera** [comment]
Another solution would be to use `(radiance:startup)` at least once before loading purplish, as then the dependencies would already be fulfilled.

**Comment by Shinmera** [comment]
I'm closing this, since it's a bug/problem with Ql/ASDF.
